#include "game/ItemInfo.hpp"

#include <bn_assert.h>
#include <bn_string_view.h>

#include "gen/TextData.hpp"

namespace ut::game
{

using Text = asset::gen::TextData;

auto ItemInfo::getName() const -> const bn::string_view&
{
    return asset::gen::getTextEn(nameData);
}

auto ItemInfo::getShortName() const -> const bn::string_view&
{
    return asset::gen::getTextEn(shortNameData);
}

auto ItemInfo::getSeriousName() const -> const bn::string_view&
{
    return asset::gen::getTextEn(seriousNameData);
}

auto ItemInfo::getDescriptions() const -> bn::vector<bn::string_view, 2>
{
    bn::vector<bn::string_view, 2> result;

    for (auto textData : descriptionDatas)
        if (textData != asset::gen::TextData::NONE)
            result.push_back(asset::gen::getTextEn(textData));

    return result;
}

static constexpr ItemInfo ITEMS[(int)ItemKind::TOTAL_COUNT] = {
    {
        ItemKind::NONE,
        ItemType::SPECIAL,
        0,
        0,
        0,
        -1,
        Text::item_name_0,
        Text::item_nameb_0,
        Text::item_names_0,
        {Text::item_desc_0_0, Text::NONE},
    },
    {
        ItemKind::MONSTER_CANDY,
        ItemType::FOOD,
        10,
        0,
        0,
        25,
        Text::item_name_1,
        Text::item_nameb_1,
        Text::item_names_1,
        {Text::item_desc_1_0, Text::NONE},
    },
    {
        ItemKind::CROQUET_ROLL,
        ItemType::FOOD,
        15,
        0,
        0,
        10,
        Text::item_name_2,
        Text::item_nameb_2,
        Text::item_names_2,
        {Text::item_desc_2_0, Text::NONE},
    },
    {
        ItemKind::STICK,
        ItemType::SPECIAL,
        0,
        0,
        0,
        150,
        Text::item_name_3,
        Text::item_nameb_3,
        Text::item_names_3,
        {Text::item_desc_3_0, Text::NONE},
    },
    {
        ItemKind::BANDAGE,
        ItemType::FOOD,
        10,
        0,
        0,
        150,
        Text::item_name_4,
        Text::item_nameb_4,
        Text::item_names_4,
        {Text::item_desc_4_0, Text::NONE},
    },
    {
        ItemKind::ROCK_CANDY,
        ItemType::FOOD,
        1,
        0,
        0,
        3,
        Text::item_name_5,
        Text::item_nameb_5,
        Text::item_names_5,
        {Text::item_desc_5_0, Text::item_desc_5_1},
    },
    {
        ItemKind::PUMPKIN_RINGS,
        ItemType::FOOD,
        8,
        0,
        0,
        3,
        Text::item_name_6,
        Text::item_nameb_6,
        Text::item_names_6,
        {Text::item_desc_6_0, Text::NONE},
    },
    {
        ItemKind::SPIDER_DONUT,
        ItemType::FOOD,
        12,
        0,
        0,
        30,
        Text::item_name_7,
        Text::item_nameb_7,
        Text::item_names_7,
        {Text::item_desc_7_0, Text::NONE},
    },
    {
        ItemKind::STOIC_ONION,
        ItemType::FOOD,
        5,
        0,
        0,
        10,
        Text::item_name_8,
        Text::item_nameb_8,
        Text::item_names_8,
        {Text::item_desc_8_0, Text::NONE},
    },
    {
        ItemKind::GHOST_FRUIT,
        ItemType::FOOD,
        16,
        0,
        0,
        10,
        Text::item_name_9,
        Text::item_nameb_9,
        Text::item_names_9,
        {Text::item_desc_9_0, Text::NONE},
    },
    {
        ItemKind::SPIDER_CIDER,
        ItemType::FOOD,
        24,
        0,
        0,
        60,
        Text::item_name_10,
        Text::item_nameb_10,
        Text::item_names_10,
        {Text::item_desc_10_0, Text::NONE},
    },
    {
        ItemKind::BUTTERSCOTCH_PIE,
        ItemType::FOOD,
        999,
        0,
        0,
        180,
        Text::item_name_11,
        Text::item_nameb_11,
        Text::item_names_11,
        {Text::item_desc_11_0, Text::NONE},
    },
    {
        ItemKind::FADED_RIBBON,
        ItemType::ARMOR,
        0,
        0,
        3,
        100,
        Text::item_name_12,
        Text::item_nameb_12,
        Text::item_names_12,
        {Text::item_desc_12_0, Text::NONE},
    },
    {
        ItemKind::TOY_KNIFE,
        ItemType::WEAPON,
        0,
        3,
        0,
        100,
        Text::item_name_13,
        Text::item_nameb_13,
        Text::item_names_13,
        {Text::item_desc_13_0, Text::NONE},
    },
    {
        ItemKind::TOUGH_GLOVE,
        ItemType::WEAPON,
        0,
        5,
        0,
        50,
        Text::item_name_14,
        Text::item_nameb_14,
        Text::item_names_14,
        {Text::item_desc_14_0, Text::NONE},
    },
    {
        ItemKind::MANLY_BANDANNA,
        ItemType::ARMOR,
        0,
        0,
        7,
        50,
        Text::item_name_15,
        Text::item_nameb_15,
        Text::item_names_15,
        {Text::item_desc_15_0, Text::NONE},
    },
    {
        ItemKind::SNOWMAN_PIECE,
        ItemType::FOOD,
        45,
        0,
        0,
        40,
        Text::item_name_16,
        Text::item_nameb_16,
        Text::item_names_16,
        {Text::item_desc_16_0, Text::NONE},
    },
    {
        ItemKind::NICE_CREAM,
        ItemType::FOOD,
        15,
        0,
        0,
        2,
        Text::item_name_17,
        Text::item_nameb_17,
        Text::item_names_17,
        {Text::item_desc_17_0, Text::NONE},
    },
    {
        ItemKind::PUPPYDOUGH_ICECREAM,
        ItemType::FOOD,
        28,
        0,
        0,
        2,
        Text::item_name_18,
        Text::item_nameb_18,
        Text::item_names_18,
        {Text::item_desc_18_0, Text::NONE},
    },
    {
        ItemKind::BISICLE,
        ItemType::FOOD,
        11,
        0,
        0,
        5,
        Text::item_name_19,
        Text::item_nameb_19,
        Text::item_names_19,
        {Text::item_desc_19_0, Text::NONE},
    },
    {
        ItemKind::UNISICLE,
        ItemType::FOOD,
        11,
        0,
        0,
        2,
        Text::item_name_20,
        Text::item_nameb_20,
        Text::item_names_20,
        {Text::item_desc_20_0, Text::NONE},
    },
    {
        ItemKind::CINNAMON_BUNNY,
        ItemType::FOOD,
        22,
        0,
        0,
        8,
        Text::item_name_21,
        Text::item_nameb_21,
        Text::item_names_21,
        {Text::item_desc_21_0, Text::NONE},
    },
    {
        ItemKind::TEMMIE_FLAKES,
        ItemType::FOOD,
        2,
        0,
        0,
        2,
        Text::item_name_22,
        Text::item_nameb_22,
        Text::item_names_22,
        {Text::item_desc_22_0, Text::NONE},
    },
    {
        ItemKind::ABANDONED_QUICHE,
        ItemType::FOOD,
        34,
        0,
        0,
        76,
        Text::item_name_23,
        Text::item_nameb_23,
        Text::item_names_23,
        {Text::item_desc_23_0, Text::NONE},
    },
    {
        ItemKind::OLD_TUTU,
        ItemType::ARMOR,
        0,
        0,
        10,
        80,
        Text::item_name_24,
        Text::item_nameb_24,
        Text::item_names_24,
        {Text::item_desc_24_0, Text::NONE},
    },
    {
        ItemKind::BALLET_SHOES,
        ItemType::WEAPON,
        0,
        7,
        0,
        80,
        Text::item_name_25,
        Text::item_nameb_25,
        Text::item_names_25,
        {Text::item_desc_25_0, Text::NONE},
    },
    {
        ItemKind::PUNCH_CARD,
        ItemType::SPECIAL,
        0,
        0,
        0,
        15,
        Text::item_name_26,
        Text::item_nameb_26,
        Text::item_names_26,
        {Text::item_desc_26_0, Text::item_desc_26_1},
    },
    {
        ItemKind::ANNOYING_DOG,
        ItemType::SPECIAL,
        0,
        0,
        0,
        999,
        Text::item_name_27,
        Text::item_nameb_27,
        Text::item_names_27,
        {Text::item_desc_27_0, Text::NONE},
    },
    {
        ItemKind::DOG_SALAD,
        ItemType::SPECIAL,
        0,
        0,
        0,
        8,
        Text::item_name_28,
        Text::item_nameb_28,
        Text::item_names_28,
        {Text::item_desc_28_0, Text::NONE},
    },
    {
        ItemKind::DOG_RESIDUE_1,
        ItemType::SPECIAL,
        0,
        0,
        0,
        3,
        Text::item_name_29,
        Text::item_nameb_29,
        Text::item_names_29,
        {Text::item_desc_29_0, Text::NONE},
    },
    {
        ItemKind::DOG_RESIDUE_2,
        ItemType::SPECIAL,
        0,
        0,
        0,
        2,
        Text::item_name_30,
        Text::item_nameb_30,
        Text::item_names_30,
        {Text::item_desc_30_0, Text::NONE},
    },
    {
        ItemKind::DOG_RESIDUE_3,
        ItemType::SPECIAL,
        0,
        0,
        0,
        4,
        Text::item_name_31,
        Text::item_nameb_31,
        Text::item_names_31,
        {Text::item_desc_31_0, Text::NONE},
    },
    {
        ItemKind::DOG_RESIDUE_4,
        ItemType::SPECIAL,
        0,
        0,
        0,
        1,
        Text::item_name_32,
        Text::item_nameb_32,
        Text::item_names_32,
        {Text::item_desc_32_0, Text::NONE},
    },
    {
        ItemKind::DOG_RESIDUE_5,
        ItemType::SPECIAL,
        0,
        0,
        0,
        4,
        Text::item_name_33,
        Text::item_nameb_33,
        Text::item_names_33,
        {Text::item_desc_33_0, Text::NONE},
    },
    {
        ItemKind::DOG_RESIDUE_6,
        ItemType::SPECIAL,
        0,
        0,
        0,
        3,
        Text::item_name_34,
        Text::item_nameb_34,
        Text::item_names_34,
        {Text::item_desc_34_0, Text::NONE},
    },
    {
        ItemKind::ASTRONAUT_FOOD,
        ItemType::FOOD,
        21,
        0,
        0,
        25,
        Text::item_name_35,
        Text::item_nameb_35,
        Text::item_names_35,
        {Text::item_desc_35_0, Text::NONE},
    },
    {
        ItemKind::INSTANT_NOODLES,
        ItemType::SPECIAL,
        0,
        0,
        0,
        50,
        Text::item_name_36,
        Text::item_nameb_36,
        Text::item_names_36,
        {Text::item_desc_36_0, Text::NONE},
    },
    {
        ItemKind::CRAB_APPLE,
        ItemType::FOOD,
        18,
        0,
        0,
        5,
        Text::item_name_37,
        Text::item_nameb_37,
        Text::item_names_37,
        {Text::item_desc_37_0, Text::NONE},
    },
    {
        ItemKind::HOT_DOG,
        ItemType::FOOD,
        20,
        0,
        0,
        10,
        Text::item_name_38,
        Text::item_nameb_38,
        Text::item_names_38,
        {Text::item_desc_38_0, Text::NONE},
    },
    {
        ItemKind::HOT_CAT,
        ItemType::FOOD,
        21,
        0,
        0,
        11,
        Text::item_name_39,
        Text::item_nameb_39,
        Text::item_names_39,
        {Text::item_desc_39_0, Text::NONE},
    },
    {
        ItemKind::GLAMBURGER,
        ItemType::FOOD,
        27,
        0,
        0,
        15,
        Text::item_name_40,
        Text::item_nameb_40,
        Text::item_names_40,
        {Text::item_desc_40_0, Text::NONE},
    },
    {
        ItemKind::SEA_TEA,
        ItemType::FOOD,
        10,
        0,
        0,
        5,
        Text::item_name_41,
        Text::item_nameb_41,
        Text::item_names_41,
        {Text::item_desc_41_0, Text::NONE},
    },
    {
        ItemKind::STARFAIT,
        ItemType::FOOD,
        14,
        0,
        0,
        10,
        Text::item_name_42,
        Text::item_nameb_42,
        Text::item_names_42,
        {Text::item_desc_42_0, Text::NONE},
    },
    {
        ItemKind::LEGENDARY_HERO,
        ItemType::FOOD,
        40,
        0,
        0,
        40,
        Text::item_name_43,
        Text::item_nameb_43,
        Text::item_names_43,
        {Text::item_desc_43_0, Text::NONE},
    },
    {
        ItemKind::CLOUDY_GLASSES,
        ItemType::ARMOR,
        0,
        0,
        5,
        50,
        Text::item_name_44,
        Text::item_nameb_44,
        Text::item_names_44,
        {Text::item_desc_44_0, Text::item_desc_44_1},
    },
    {
        ItemKind::TORN_NOTEBOOK,
        ItemType::WEAPON,
        0,
        2,
        0,
        50,
        Text::item_name_45,
        Text::item_nameb_45,
        Text::item_names_45,
        {Text::item_desc_45_0, Text::item_desc_45_1},
    },
    {
        ItemKind::STAINED_APRON,
        ItemType::ARMOR,
        0,
        0,
        11,
        100,
        Text::item_name_46,
        Text::item_nameb_46,
        Text::item_names_46,
        {Text::item_desc_46_0, Text::NONE},
    },
    {
        ItemKind::BURNT_PAN,
        ItemType::WEAPON,
        0,
        10,
        0,
        100,
        Text::item_name_47,
        Text::item_nameb_47,
        Text::item_names_47,
        {Text::item_desc_47_0, Text::NONE},
    },
    {
        ItemKind::COWBOY_HAT,
        ItemType::ARMOR,
        0,
        5,
        12,
        100,
        Text::item_name_48,
        Text::item_nameb_48,
        Text::item_names_48,
        {Text::item_desc_48_0, Text::item_desc_48_1},
    },
    {
        ItemKind::EMPTY_GUN,
        ItemType::WEAPON,
        0,
        12,
        0,
        100,
        Text::item_name_49,
        Text::item_nameb_49,
        Text::item_names_49,
        {Text::item_desc_49_0, Text::item_desc_49_1},
    },
    {
        ItemKind::HEART_LOCKET,
        ItemType::ARMOR,
        0,
        0,
        15,
        250,
        Text::item_name_50,
        Text::item_nameb_50,
        Text::item_names_50,
        {Text::item_desc_50_0, Text::NONE},
    },
    {
        ItemKind::WORN_DAGGER,
        ItemType::WEAPON,
        0,
        15,
        0,
        250,
        Text::item_name_51,
        Text::item_nameb_51,
        Text::item_names_51,
        {Text::item_desc_51_0, Text::NONE},
    },
    {
        ItemKind::REAL_KNIFE,
        ItemType::WEAPON,
        0,
        99,
        0,
        500,
        Text::item_name_52,
        Text::item_nameb_52,
        Text::item_names_52,
        {Text::item_desc_52_0, Text::NONE},
    },
    {
        ItemKind::THE_LOCKET,
        ItemType::ARMOR,
        0,
        0,
        99,
        500,
        Text::item_name_53,
        Text::item_nameb_53,
        Text::item_names_53,
        {Text::item_desc_53_0, Text::NONE},
    },
    {
        ItemKind::BAD_MEMORY,
        ItemType::SPECIAL,
        -1,
        0,
        0,
        300,
        Text::item_name_54,
        Text::item_nameb_54,
        Text::item_names_54,
        {Text::item_desc_54_0, Text::NONE},
    },
    {
        ItemKind::DREAM,
        ItemType::FOOD,
        17,
        0,
        0,
        250,
        Text::item_name_55,
        Text::item_nameb_55,
        Text::item_names_55,
        {Text::item_desc_55_0, Text::NONE},
    },
    {
        ItemKind::UNDYNES_LETTER,
        ItemType::SPECIAL,
        0,
        0,
        0,
        -1,
        Text::item_name_56,
        Text::item_nameb_56,
        Text::item_names_56,
        {Text::item_desc_56_0, Text::NONE},
    },
    {
        ItemKind::UNDYNES_LETTER_EX,
        ItemType::SPECIAL,
        0,
        0,
        0,
        -1,
        Text::item_name_57,
        Text::item_nameb_57,
        Text::item_names_57,
        {Text::item_desc_57_0, Text::NONE},
    },
    {
        ItemKind::POPATO_CHISPS,
        ItemType::FOOD,
        13,
        0,
        0,
        35,
        Text::item_name_58,
        Text::item_nameb_58,
        Text::item_names_58,
        {Text::item_desc_58_0, Text::NONE},
    },
    {
        ItemKind::JUNK_FOOD,
        ItemType::FOOD,
        17,
        0,
        0,
        1,
        Text::item_name_59,
        Text::item_nameb_59,
        Text::item_names_59,
        {Text::item_desc_59_0, Text::NONE},
    },
    {
        ItemKind::MYSTERY_KEY,
        ItemType::SPECIAL,
        0,
        0,
        0,
        -1,
        Text::item_name_60,
        Text::item_nameb_60,
        Text::item_names_60,
        {Text::item_desc_60_0, Text::NONE},
    },
    {
        ItemKind::FACE_STEAK,
        ItemType::FOOD,
        60,
        0,
        0,
        14,
        Text::item_name_61,
        Text::item_nameb_61,
        Text::item_names_61,
        {Text::item_desc_61_0, Text::item_desc_61_1},
    },
    {
        ItemKind::HUSH_PUPPY,
        ItemType::FOOD,
        65,
        0,
        0,
        150,
        Text::item_name_62,
        Text::item_nameb_62,
        Text::item_names_62,
        {Text::item_desc_62_0, Text::NONE},
    },
    {
        ItemKind::SNAIL_PIE,
        ItemType::SPECIAL,
        0,
        0,
        0,
        350,
        Text::item_name_63,
        Text::item_nameb_63,
        Text::item_names_63,
        {Text::item_desc_63_0, Text::NONE},
    },
    {
        ItemKind::TEMY_ARMOR,
        ItemType::ARMOR,
        0,
        10,
        20,
        500,
        Text::item_name_64,
        Text::item_nameb_64,
        Text::item_names_64,
        {Text::item_desc_64_0, Text::item_desc_64_1},
    },
};

auto ItemInfo::get(ItemKind kind) -> const ItemInfo&
{
    BN_ASSERT((int)kind < (int)ItemKind::TOTAL_COUNT);

    return ITEMS[(int)kind];
}

} // namespace ut::game
