from datetime import datetime

def write_timestamp(f, gen_by: str):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    f.write(f"// Auto-generated by `{gen_by}` on {timestamp}\n")
    f.write(f"// DO NOT EDIT this file;  It will be overwritten on next build!\n\n")
